### ISSUE TITLE
Questions regarding glpk-online

### ISSUE THREAD

**Issue by SebastianDaneli** [cocoto/glpk-online#11]
Hi 

I'm wondering if I can see the time it takes for the program to solve a problem somewhere?
I don't see it in the log. Also, where do I see the number of iterations and the number of nodes?

Thanks

**Comment by cocoto** [comment]
Dear Sebastian,

You're right, we should include time measurement in the summary tab.
I add the idea in the todo list 😄 

For iterations and the number of nodes (supposed MILP/MBLP) you can extract some info from the **log tab** :

```
Integer optimization begins...
+37: mip = not found yet >= -inf  (1; 0)
+45: >>>>> 17820 >= 11569   35.1% (6; 0)
+48: >>>>> 17410 >= 13345   23.3% (3; 4)
+48: mip = 17410 >= tree is empty   0.0% (0; 11)
```

Corresponding to those info : 

> *  the current number of iterations performed by the simplex solver;
> *  the objective value for the best known integer feasible solution, which is upper (minimization) or lower (maximization) global bound for optimal solution of the original mip problem;
> *  the best local bound for active nodes, which is lower (minimization) or upper (maximization) global bound for optimal solution of the original mip problem;
> *  the relative mip gap, in percents;
> *  the number of open (active) subproblems;
> *  the number of completely explored subproblems, i.e. whose nodes have been removed from the tree.

**Comment by SebastianDaneli** [comment]
So 48 is the number of simplex iterations and 11 is the number of nodes when the problem is solved?

**Comment by cocoto** [comment]
Yes, after 48 simplex iterations over 11 nodes explored,
The algorithm have closed every branch of the discrete variable search tree.

**Comment by SebastianDaneli** [comment]
Thx.
