### ISSUE TITLE
Feature request: pre-fill model field with content from URL, store model in URL

### ISSUE THREAD

**Issue by ojdo** [cocoto/glpk-online#6]
And now the obligatory feature request: as most models which one would like to solve in the browser happen to be rather short (<2 kB), one could store them in the page's URL. That way, one can store (bookmark) and share (send a long URL) models easily.

    https://cocoto.github.io/glpk-online/?m=minimize%20obj:...#

Sketch: a button encodes the current content of the text field [URL-safe](https://en.wikipedia.org/wiki/Percent-encoding) and sets the current URL with a parameter. On initial page load, if `m=...` is set, pre-fill the editor with the decoded string.

Would you be fine with a MR that adds this behaviour?

**Comment by cocoto** [comment]
Yes of course, every proposal features are welcome !
There is already an autobackup of the model in LocalStorage, why not use the encode function for the two systems

**Comment by cocoto** [comment]
Added with m #7
